### ISSUE TITLE
Versionhallinnan käyttöönotto

### ISSUE THREAD

**Issue by ilkkamtk** [vesavvo/Python_Ohjelmistoteema#1]
Opettajan kantilta public repo olisi kivempi, kuin private. Ainakin jos on tarkoitus olla sellainen repo, jossa on tarkastettavia tehtäviä. Opettajan toki voi lisätä collaboraattoriksi, mutta siitä tulee välillä isoja määriä sähköpostia, kun kaikkien opiskelijoiden repot rupee lähettämään tietoturvavaroituksia.

Näppärä työkalu gitignoren tekoon: https://www.toptal.com/developers/gitignore. Tuonne syötetään käytetty IDE ja ohjelmointikieli, niin saa valmiin gitignoren.

**Comment by vesavvo** [comment]
Päätettiin tehdä private repot tässä vaiheessa datan integriteettisyistä. Sähköpostispämmit hoituu filttereillä.
