### ISSUE TITLE
Typo in exercises

### ISSUE THREAD

**Issue by Arc4517** [vesavvo/Python_Ohjelmistoteema#2]
3. Conditional structures (if)
exercise 2 lists cabin types with type B appearing twice, instead of C:
The finnish version is properly listed LUX -> A -> B -> C

LUX: upper-deck cabin with a balcony.
A: above the car deck, equipped with a window.
B: windowless cabin above the car deck.
B: windowless cabin below the car deck

**Comment by vesavvo** [comment]
Thanks, fixed.
