### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Arc4517** [vesavvo/Python_Ohjelmistoteema#4]
In the exercise 5.1:
"Write a program that asks the user how many dice to roll. The program rolls all the dice once and prints out **the the** sum of the numbers. Use a for loop."
"the" is repeated twice.

**Comment by Arc4517** [comment]
another typo in 5.3
"For example, number 13 is a prime number as can only be divided by 1 or 13 so that the result is an integer."
->
"For example, number 13 is a prime number as **it** can only be divided by 1 or 13 so that the result is an integer."

**Comment by Arc4517** [comment]
also:
use "the" when referring to specific numbers ex:
"**the** number 21"
"**the** number 13"
'"by **the** numbers 3 and 7."
OR
just "21"
"13"
"3 and 7"

and suggestion
"On the other hand, number 21 for example is not a prime number as it can be also be divided by numbers 3 and 7."
->
"On the other hand, number 21 for example is not a prime number as it **is divisible** by numbers 3 and 7."
is a lot more readable.

**Comment by vesavvo** [comment]
Corrected, thanks!
